spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  logging:
    level:
      root: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5432/refcloudapi
    username: refcloudapi
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:4444

ga4gh:
  refcloud:
    security:
      cors:
        allowed-origins:
          - http://127.0.0.1:3000
        allowed-methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        allowed-headers:
          - "*"
        exposed-headers:
          - "Authorization"
        allow-credentials: true
        max-age: 3600
      kratos:
        public-base-url: "http://127.0.0.1:4433"
        webhook:
          username: kratos_webhook_user
          password: secret
    drs:
      scheme: http
      host-domain: 127.0.0.1:8080
      service-info:
        id: org.ga4gh.refcloud.drs.local
        name: GA4GH Reference Cloud DRS Service (Local Dev Environment)
        type:
          group: org.ga4gh
          artifact: drs
          version: 1.5
        description: GA4GH reference implementation of the Data Repository Service (DRS) specification
        organization:
          name: Global Alliance for Genomics and Health (GA4GH)
          url: https://ga4gh.org
        contact-url: info@ga4gh.org
        documentation-url: https://github.com/ga4gh/ga4gh-reference-cloud
        created-at: 2026-06-05T20:00:00Z
        updated-at: 2026-06-05T20:00:00Z
        environment: dev
        version: v0.1.0
        drs:
          max-bulk-length-request: 10
